paths:
  raw_dir: "data/raw/cmu_cert_r5.2"
  processed_dir: "data/processed"
  extract_dir: "data/raw/cmu_cert_r5.2/r5.2"

# CMU CERT Dataset Article ID on Figshare
download:
  article_id: "12841247"
  target_files: 
    - "r5.2.tar.bz2"
    - "answers.tar.bz2"